use_frameworks!

target 'SublimateSync_Example' do
  pod 'SublimateSync', :path => '../../'

  target 'SublimateSync_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
